### ISSUE TITLE
Consolidate Installer and block-tracker

### ISSUE THREAD

**Issue by framps** [ajacobsen/block-tracker#9]
I think developers life will become much easier if both scripts are consolidated. No duplicate code for I18N needed any more. If you agree I'll work on this and create a Pull request when I'm done

**Comment by ajacobsen** [comment]
I agree. :)

**Comment by framps** [comment]
You have to take care to update the documentation how to install block-tracker :-)
I'll going to use following invocation options:
1) -- install -> just install script
2) -- uninstall -> undo installation
3) -- disable -> disable option

4) Maybe an --enable option would be useful also to implement. 

I'll work on 1-3. If you want to work on 4) please wait for my pull request.

**Comment by framps** [comment]
I added the enable function also :-) See my pull request https://github.com/ajacobsen/block-tracker/pulls

**Comment by ajacobsen** [comment]
Closed by #10
